Repository piskoviste/pisek, pull requests merged in 2024-08, with the labels that each got.

#197 Generate inputs on the fly
  README.md
  config-v3-documentation
  fixtures/guess/config
  fixtures/pisek/configs/interactive
  fixtures/sum_cms/check.py
  fixtures/sum_cms/check_loose.py
  fixtures/sum_cms/sample_02.bad
  fixtures/sum_kasiopea/check.py
  fixtures/sum_kasiopea/check_loose.py
  pisek/__main__.py
  pisek/cms/__init__.py
  pisek/cms/result.py
  pisek/config/cms-defaults
  pisek/config/config_hierarchy.py
  pisek/config/config_types.py
  pisek/config/kasiopea-defaults
  pisek/config/task_config.py
  pisek/config/update_config.py
  pisek/env/base_env.py
  pisek/env/env.py
  pisek/jobs/jobs.py
  pisek/jobs/task_pipeline.py
  pisek/server.py
  pisek/task_jobs/checker.py
  pisek/task_jobs/compile.py
  pisek/task_jobs/completeness_check.py
  pisek/task_jobs/data.py
  pisek/task_jobs/data/__init__.py
  pisek/task_jobs/data/data.py
  pisek/task_jobs/data/manager.py
  pisek/task_jobs/generator.py
  pisek/task_jobs/generator/__init__.py
  pisek/task_jobs/generator/base_classes.py
  pisek/task_jobs/generator/cms_old.py
  pisek/task_jobs/generator/input_info.py
  pisek/task_jobs/generator/manager.py
  pisek/task_jobs/generator/opendata_v1.py
  pisek/task_jobs/judge.py
  pisek/task_jobs/program.py
  pisek/task_jobs/solution/__init__.py
  pisek/task_jobs/solution/manager.py
  pisek/task_jobs/solution/solution.py
  pisek/task_jobs/solution/solution_result.py
  pisek/task_jobs/solution/verdicts_eval.py
  pisek/task_jobs/task_job.py
  pisek/task_jobs/task_manager.py
  pisek/task_jobs/testing_log.py
  pisek/task_jobs/tools.py
  pisek/utils/paths.py
  pisek/visualize.py
  tests/test_cms.py
  tests/test_kasiopea.py
Labels: high priority, feature / improvement

#199 Judge, Solution: Cleanup global variables not used anymore
  pisek/task_jobs/judge.py
  pisek/task_jobs/solution/solution.py
Labels: debt

#200 Pisek Gen V1
  README.md
  fixtures/odd_stub/config
  fixtures/odd_stub/gen.py
  pisek/config/config_types.py
  pisek/license.py
  pisek/task_jobs/generator/base_classes.py
  pisek/task_jobs/generator/manager.py
  pisek/task_jobs/generator/opendata_v1.py
  pisek/task_jobs/generator/pisek_gen_v1.py
  pisek/task_jobs/task_job.py
  pyproject.toml
Labels: feature / improvement

#201 Did you mean
  config-v3-documentation
  fixtures/guess/config
  pisek/config/cms-defaults
  pisek/config/config-description
  pisek/config/config-v3-documentation
  pisek/config/config_hierarchy.py
  pisek/config/config_types.py
  pisek/config/did_you_mean.py
  pisek/config/task_config.py
  pisek/config/update_config.py
  pisek/task_jobs/completeness_check.py
  pisek/task_jobs/judge.py
  pyproject.toml
Labels: high priority, bug, feature / improvement

#207 Add generator docs
  config-v3-documentation
  dev-docs/Jobs.md
  docs/generator.md
  pisek/config/global-defaults
  pisek/config/task_config.py
  pisek/task_jobs/generator/manager.py
Labels: feature / improvement, documentation

#208 PisekV1 generator fixing
  config-v3-documentation
  docs/generator.md
  fixtures/odd_stub/config
  pisek/config/config_types.py
  pisek/task_jobs/generator/base_classes.py
  pisek/task_jobs/generator/manager.py
  pisek/task_jobs/generator/pisek_v1.py
  pisek/task_jobs/program.py
Labels: high priority, bug

#209 Improve config parsing
  pisek/config/config_errors.py
  pisek/config/config_hierarchy.py
  pisek/config/task_config.py
Labels: high priority, bug, feature / improvement

#211 ConfigDocs: Improvements
  config-v2-documentation
  config-v3-documentation
Labels: documentation
