Repository piskoviste/pisek, pull requests merged in 2025-09, with the labels that each got.

#442 refactor: ProgramType -> ProgramRole
  docs/config-v3-documentation
  pisek/config/config_types.py
  pisek/config/task_config.py
  pisek/config/update_config.py
  pisek/task_jobs/checker/cms_judge.py
  pisek/task_jobs/checker/opendata_judge.py
  pisek/task_jobs/generator/cms_old.py
  pisek/task_jobs/generator/opendata_v1.py
  pisek/task_jobs/generator/pisek_v1.py
  pisek/task_jobs/program.py
  pisek/task_jobs/solution/solution.py
  pisek/task_jobs/validator/validator_base.py
Labels: high priority, code

#437 docs(examples): Add cms-batch task
  examples/cms-batch/.gitignore
  examples/cms-batch/config
  examples/cms-batch/gen.py
  examples/cms-batch/judge.py
  examples/cms-batch/sample.in
  examples/cms-batch/sample.out
  examples/cms-batch/solve_all_ones.java
  examples/cms-batch/solve_last_big.cpp
  examples/cms-batch/solve_small_k.py
  examples/cms-batch/solve_spread/Cargo.lock
  examples/cms-batch/solve_spread/Cargo.toml
  examples/cms-batch/solve_spread/src/main.rs
  examples/cms-batch/statement.md
  examples/cms-batch/validate.py
Labels: good first issue, documentation

#439 docs(examples): Add example organization configs
  examples/organization-configs/README.md
  examples/organization-configs/cms-base-v1
  examples/organization-configs/cms-batch-v1
  examples/organization-configs/cms-communication-v1
  examples/organization-configs/opendata-v1
Labels: documentation

#432 Add bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: blocked

#423 feat(cms): support oi_restricted feedback level
  docs/config-v2-documentation
  docs/config-v3-documentation
  pisek/config/config_types.py
Labels: good first issue, CMS

#454 fix(pyproject): Update homepage & issues urls
  pyproject.toml
Labels: documentation

#450 Run envs
  docs/config-v3-documentation
  pisek/config/config-description
  pisek/config/config_description.py
  pisek/config/config_hierarchy.py
  pisek/config/config_tools.py
  pisek/config/task_config.py
  pisek/task_jobs/program.py
  tests/util.py
Labels: high priority, configs, run

#455 fix(main): RuntimeError -> assert False
  pisek/__main__.py
Labels: code
